// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcXaHjALoafya8Lb9ucGhm6xoTGSA2a2Q',
    appId: '1:236560125204:web:38804c8cd42e5beb93c601',
    messagingSenderId: '236560125204',
    projectId: 'reklama-app',
    authDomain: 'reklama-app.firebaseapp.com',
    storageBucket: 'reklama-app.appspot.com',
    measurementId: 'G-0ERD8VVE8N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClfNF4aRk01mxibz1Xplkt78bRdbt7ehM',
    appId: '1:236560125204:android:40184bebb8b593da93c601',
    messagingSenderId: '236560125204',
    projectId: 'reklama-app',
    storageBucket: 'reklama-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBk3HFf-KdspmHkP_1w_rOvtg6UOqy5V28',
    appId: '1:236560125204:ios:aa2e7e9dc6b7d43693c601',
    messagingSenderId: '236560125204',
    projectId: 'reklama-app',
    storageBucket: 'reklama-app.appspot.com',
    iosClientId: '236560125204-tje1l3hatfc3kpoegtk53pvqlmafrjt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.reklamaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBk3HFf-KdspmHkP_1w_rOvtg6UOqy5V28',
    appId: '1:236560125204:ios:aa2e7e9dc6b7d43693c601',
    messagingSenderId: '236560125204',
    projectId: 'reklama-app',
    storageBucket: 'reklama-app.appspot.com',
    iosClientId: '236560125204-tje1l3hatfc3kpoegtk53pvqlmafrjt3.apps.googleusercontent.com',
    iosBundleId: 'com.example.reklamaApp',
  );
}
